#!/usr/bin/python

# This file is part of eVic SDK.
#
# eVic SDK is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# eVic SDK is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with eVic SDK.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright (C) 2016 ReservedField

import sys
import argparse
from PIL import Image
from common.bitmap import Bitmap

# Parse command-line arguments
parser = argparse.ArgumentParser(description='Decode images from eVic SDK bitmap format.')
parser.add_argument('width', metavar='width', type=int, help='image width')
parser.add_argument('height', metavar='height', type=int, help='image height')
parser.add_argument('inFileName', metavar='input', type=str, help='input file name')
parser.add_argument('outFileName', metavar='output', type=str, help='output file name')
parser.add_argument('--invert', dest='invert', action='store_const',
	const=True, default=False, help='invert image colors')
args = parser.parse_args()

# Read input file
with open(args.inFileName, 'rb') as inFile:
	imgBytes = inFile.read()

# Decode SDK bitmap
bitmap = Bitmap.fromBytes(imgBytes, args.width, args.height)
if args.invert:
	bitmap.invert()

# Print image
print(bitmap.toAsciiArtStr(False))

# Write output file
bitmap.img.save(args.outFileName)
